apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-backend-deployment
spec:
  selector:
    matchLabels:
      app: busybox-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox-backend

    spec:
      containers:
        - name: busybox-backend
          image: jahedulislam/busybox-backend:latest
          ports:
            - containerPort: 8080

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: db-config
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: dbName
                  name: db-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mysql-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: busybox-backend-service
spec:
  selector:
    app: busybox-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
  type: ClusterIp