apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: busybox-ingress
  # this portion is for the CA
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"

spec:
  # this portion is for th CA
  ingressClassName: traefik
  tls:
    - hosts:
        - localhost
      secretName: local-tls
  rules:
    - host: localhost
      http:
        paths:
          - path: /busyBox
            pathType: Prefix
            backend:
              service:
                name: busybox-backend-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80