apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-cert
  namespace: default
spec:
  secretName: busybox-tls-secret  # Secret name for the TLS certificate
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - BusyBox
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - prod.busybox.space
  issuerRef:
    name: letsencrypt-prod  # Match this with the ClusterIssuer name
    kind: ClusterIssuer
    group: cert-manager.io
