kind: Service # Kubernetes resource kind we are creating
apiVersion: v1 # Kubernetes API version
metadata:
  name: frontend-service
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort