spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    hikari:
      initialization-fail-timeout: 0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jahedulBusybox
#    hikari:
#      initialization-fail-timeout: 0
#    username: root
#    password: 12345678
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update