name: Docker Image CI for busybox backend

on:
  push:
    branches: [ "main" ]


jobs:

  build-image:
    name: Build the docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker compose build

  push_to_registry:

    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -  name: List all Docker images
         run: docker images
          
      - name: Push the image to docker hub
        run: docker push jahedulislam/busybox-backend-amd64:1.0
